[package]
name = "close-to-light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
tokio = { version = "1", features = ["rt"] }
geng = "0.17.0"
geng-utils = "0.3.0"
parry2d = "0.13.5"
serde = { version = "1.0.183", features = ["derive"] }
nertboard-client = { git = "https://github.com/Nertsal/nertboard", rev = "430f048e4d50cb34246ce2bd466e1d1689647d99" }
enum-iterator = "1.4.1"

[patch.crates-io]
async-broadcast = { git = "https://github.com/kuviman/async-broadcast", branch = "fix-wasm" } # TODO: until https://github.com/smol-rs/async-broadcast/pull/47 is merged
