[package]
name = "geng_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
geng = { git = "https://github.com/geng-engine/geng" }
geng_utils = { git = "https://github.com/nertsal/geng_utils" }
parry2d = "0.13.5"
serde = { version = "1.0.183", features = ["derive"] }
