[package]
name = "close-to-light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
geng = "0.17.0"
geng-utils = "0.3.0"
parry2d = "0.13.5"
serde = { version = "1.0.183", features = ["derive"] }
jornet = { git = "https://github.com/kuviman/jornet" }
enum-iterator = "1.4.1"
