name: Clean up Deployments

on:
  push:
    branches: [github-pages, main, dev]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - name: Delete inactive deployments
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.ref_name }}
          ref: ${{ github.ref_name }}
          onlyRemoveDeployments: true
